{
 "title": "DayZ RCON",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "dayz_server",
    "label": "Server",
    "query": {
     "query": "label_values(a2s_info_time,server)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(a2s_info_time{server=~\"$dayz_server\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "[![logo](https://github.com/WoozyMasta/dayz-exporter/raw/master/assets/dayz-exporter.png)](https://github.com/WoozyMasta/dayz-exporter)"
   }
  },
  {
   "title": "Servers Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(a2s_info_players_slots{instance=~\"$instance\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Slots Count Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(a2s_info_players_slots{instance=~\"$instance\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "GUID Bans Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bercon_ban_guid_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Bans Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bercon_ban_ip_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Players Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(a2s_info_players_online{instance=~\"$instance\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Top 20 Players",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(20, sum by(name, guid) (\r\n  count_over_time(\r\n    bercon_player_ping_seconds{\r\n      instance=~\"$instance\",\r\n      guid!=\"00000000000000000000000000000000\"\r\n    }[$__range]\r\n  )\r\n) * 15)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top Players Country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(country) (20, count by(country) (bercon_player_ping_seconds{instance=~\"$instance\"}))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Servers Players Load",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(a2s_info_players_online{instance=~\"$instance\"} + a2s_info_players_queue{instance=~\"$instance\"}) / a2s_info_players_slots{instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(namedprocess_namegroup_oldest_start_time_seconds>0)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Servers Mean Query Ping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(a2s_info_ping_seconds{instance=~\"$instance\"}) without(version)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total busy players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(a2s_info_players_queue{instance=~\"$instance\"})",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum(bercon_players_lobby{instance=~\"$instance\"})",
     "legendFormat": "Lobby"
    },
    {
     "expr": "sum(bercon_players_invalid{instance=~\"$instance\"})",
     "legendFormat": "Invalid"
    }
   ]
  },
  { "title": "Server: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "instance" },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "a2s_info_players_online{instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "a2s_info_players_slots{instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Online players",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "a2s_info_players_slots{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "a2s_info_players_online{instance=~\"$instance\"}",
     "legendFormat": "online"
    },
    {
     "expr": "a2s_info_time{instance=~\"$instance\"} / 1e9",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(a2s_info_players_queue{instance=~\"$instance\"})",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum(bercon_players_lobby{instance=~\"$instance\"})",
     "legendFormat": "Lobby"
    },
    {
     "expr": "sum(bercon_players_invalid{instance=~\"$instance\"})",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Players",
   "type": "table",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bercon_player_ping_seconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time on server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "a2s_info_time{instance=~\"$instance\"} / 1e9",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Players ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(name,guid) (bercon_player_ping_seconds{instance=~\"$instance\", guid!=\"00000000000000000000000000000000\"}) < 65535",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Mean Query Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(a2s_info_ping_seconds{instance=~\"$instance\"}) without (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "a2s_info_players_online{instance=~\"$instance\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Top Players Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(country) (20, count by(country) (bercon_player_ping_seconds{instance=~\"$instance\"}))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Top 15 Players",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(15, sum by(name, guid) (\r\n  count_over_time(\r\n    bercon_player_ping_seconds{\r\n      instance=~\"$instance\",\r\n      guid!=\"00000000000000000000000000000000\"\r\n    }[$__range]\r\n  )\r\n) * 15)",
     "legendFormat": "{{name}} [{{guid}}]"
    }
   ]
  }
 ]
}