{
 "title": "System Processes Metrics",
 "description": "Show Linux Process information as captured by \n https://github.com/ncabatoff/process-exporter  designed for PMM",
 "tags": [ "Insight" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(namedprocess_namegroup_num_procs, instance)"
   },
   {
    "name": "processes",
    "label": "Processes",
    "query": "label_values(namedprocess_namegroup_cpu_user_seconds_total{instance=~\"$host\"},groupname)"
   },
   { "name": "Filters" },
   {
    "name": "interval",
    "query": "5s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Process Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processes by uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time()-(namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$host\"}>0)"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Count processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(groupname) (namedprocess_namegroup_num_procs{groupname=~\"$processes\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Total CPU time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\"}[$interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Read bytes total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\"}[$interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Write bytes total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\"}[$interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Residental memory total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(groupname) (namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual memory total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(groupname) (namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Swapped memory total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(groupname) (namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top processes by Total CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Running processes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states{groupname=~\"$processes\", state=\"Running\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Sleeping processes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states{groupname=~\"$processes\", state=\"Sleeping\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Waiting processes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states{groupname=~\"$processes\", state=\"Waiting\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Zombie processes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states{groupname=~\"$processes\", state=\"Zombie\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Other processes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_states{groupname=~\"$processes\", state=\"Other\",instance=~\"$host\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Top processes by Used  memory",
   "type": "timeseries",
   "description": "Memory Used by Processes, counted as Resident Memory + Space used in Swap Space",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\", instance=~\"$host\"}[1m]) + ignoring(memtype) avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\", instance=~\"$host\"}[1m])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,\n(avg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[$interval]) \nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$host\"}[5m])\n))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$host\"}[5m])))\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Swapped Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,(\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[$interval])\nor\navg_over_time(namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\",instance=~\"$host\"}[5m])))\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Disk IO Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Top processes by Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5,(rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5,(rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or irate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process and Thread Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Top processes by number of  processes instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) \nor max_over_time(namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by number of threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Context Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Top Processes by Voluntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"voluntary\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top Processes by  Non-Voluntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[$interval]) or\nirate(namedprocess_namegroup_context_switches_total{groupname=~\"$processes\",instance=~\"$host\",ctxswitchtype=\"nonvoluntary\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Top processes by Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,(max_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by File Descriptor Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_worst_fd_ratio{groupname=~\"$processes\",instance=~\"$host\"}[5m])\n))*100",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Page Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Top processes by Major Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_major_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Minor Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,(\nrate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[$interval]) or\nirate(namedprocess_namegroup_minor_page_faults_total{groupname=~\"$processes\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Process Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Top running processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Running\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top of processes waiting on IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,(\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[$interval]) or\nmax_over_time(namedprocess_namegroup_states{instance=~\"$host\", groupname=~\"$processes\", state=\"Waiting\"}[5m])))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Kernel Waits (WCHAN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel waits for $processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan) )",
       "legendFormat": "{{wchan}}"
      }
     ]
    },
    {
     "title": "Kernel wait Details for $processes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=~\"$host\", groupname=~\"$processes\"}[$interval])) by (wchan,groupname) )",
       "legendFormat": "{{groupname}} : {{wchan}}"
      }
     ]
    }
   ]
  }
 ]
}