name: Scan release

on:
  release:
    types: [published, created, released, edited]

permissions:
  contents: write

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            ./dayz-exporter-darwin-arm64
            ./dayz-exporter-linux-amd64
            ./dayz-exporter-linux-arm64
            ./dayz-exporter-windows-amd64.exe
            ./dayz-exporter-windows-386.exe
